-- ============================================================
--  Anjuroela Fit - Esquema para Supabase (replica 1:1 de SQLite)
--  Ejecutar completo en: Supabase Dashboard > SQL Editor.
--  Cada tabla local tiene su equivalente idÃ©ntico en nombre y columnas.
--  Mapeo de tipos: INTEGER -> integer, REAL -> double precision,
--  TEXT -> text, flags 0/1 -> integer (igual que en SQLite).
-- ============================================================

-- Limpieza idempotente previa: si la tabla 'users' aún conserva la columna
-- legacy 'id' (estructura int8 con identidad), se elimina por completo el
-- conjunto de tablas que dependían de ella para que las definiciones
-- siguientes (basadas en email) se creen desde cero. Incluye meals_v2 y
-- user_row_owners porque ambas referenciaban users(id) mediante FK y, tras el
-- DROP CASCADE de users, mantendrían la columna legacy bigint que el
-- 'CREATE TABLE IF NOT EXISTS' posterior ya no corregiría.
-- Idempotente: en instalaciones ya migradas (sin 'id'), el bloque no hace nada.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'users' and column_name = 'id'
  ) then
    drop table if exists public.user_profiles cascade;
    drop table if exists public.nutrition_profile cascade;
    drop table if exists public.meals_v2 cascade;
    drop table if exists public.user_row_owners cascade;
    drop table if exists public.users cascade;
  end if;
end $$;

-- ---------------- usuarios ----------------
-- El EMAIL es la clave primaria (identidad unica de la cuenta, igual que en
-- SQLite local); el antiguo id identity queda fuera del modelo.
create table if not exists public.users (
  email text primary key,
  name text not null,
  password_hash text,
  auth_provider text default 'local',
  created_at text default (now()::text)
);

-- UNIQUE(email) (redundante con la PK) para compatibilidad con el upsert por
-- correo idempotente. Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.users'::regclass
      and contype = 'u'
      and conname = 'users_email_key'
  ) then
    alter table public.users
      add constraint users_email_key unique (email);
  end if;
end $$;

create table if not exists public.user_profiles (
  user_id text primary key,
  age integer,
  height double precision,
  current_weight double precision,
  target_weight double precision,
  goal_weeks integer,
  goal_date text,
  goal_status text default 'active',
  username text,
  created_at text default (now()::text),
  constraint user_profiles_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

-- UNIQUE(user_id): un solo perfil por usuario (necesario para el upsert
-- por user_id desde la app).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.user_profiles'::regclass
      and contype = 'u'
      and conname = 'user_profiles_user_id_key'
  ) then
    alter table public.user_profiles
      add constraint user_profiles_user_id_key unique (user_id);
  end if;
end $$;

-- ---------------- catalogo de ejercicios ----------------
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  muscle_group text,
  description text,
  created_at text default (now()::text)
);

create table if not exists public.body_parts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  is_active integer not null default 1,
  created_at text default (now()::text)
);

create table if not exists public.exercises_v2 (
  id bigint generated by default as identity primary key,
  name text not null,
  body_part_id bigint not null,
  description text,
  equipment text,
  is_active integer not null default 1,
  created_at text default (now()::text),
  constraint exercises_v2_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade
);

-- ---------------- rutinas (legacy / solo copia) ----------------
create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  completed integer not null default 0,
  date text default (current_date::text),
  created_at text default (now()::text)
);

create table if not exists public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null,
  exercise_id bigint not null,
  sets integer not null default 3,
  reps integer not null default 10,
  weight double precision,
  constraint workout_exercises_workout_fk
    foreign key (workout_id) references public.workouts (id) on delete cascade,
  constraint workout_exercises_exercise_fk
    foreign key (exercise_id) references public.exercises (id) on delete cascade
);

-- ---------------- comidas (legacy / solo copia) ----------------
create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  name text not null,
  calories integer,
  protein double precision,
  carbs double precision,
  fats double precision,
  date text default (current_date::text),
  created_at text default (now()::text)
);

create table if not exists public.meals_v2 (
  id bigint generated by default as identity primary key,
  user_id text not null,
  date text not null,
  meal_type text not null
    check (meal_type in ('desayuno', 'almuerzo', 'cena', 'snack')),
  image_uri text,
  description text,
  calories double precision default 0,
  protein_g double precision default 0,
  carbs_g double precision default 0,
  fat_g double precision default 0,
  notes text,
  created_at text default (now()::text),
  constraint meals_v2_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

create table if not exists public.progress (
  id bigint generated by default as identity primary key,
  date text default (current_date::text),
  weight double precision,
  body_fat double precision,
  muscle_mass double precision,
  created_at text default (now()::text)
);

-- ---------------- planificacion semanal ----------------
create table if not exists public.weekly_schedule (
  id bigint generated by default as identity primary key,
  day_of_week text not null unique,
  body_part_id bigint,
  constraint weekly_schedule_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete set null
);

-- UNIQUE(day_of_week): un solo registro de plan por día de la semana
-- (upsert por conflicto en day_of_week desde la app). Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.weekly_schedule'::regclass
      and contype = 'u'
      and conname = 'weekly_schedule_day_of_week_key'
  ) then
    alter table public.weekly_schedule
      add constraint weekly_schedule_day_of_week_key unique (day_of_week);
  end if;
end $$;

create table if not exists public.day_muscles (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  position integer not null default 0,
  completed integer not null default 0,
  completed_date text,
  constraint day_muscles_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint day_muscles_day_body_unique unique (day_of_week, body_part_id)
);

-- UNIQUE(day_of_week, body_part_id): no asignar el mismo músculo dos veces el
-- mismo día (upsert por conflicto compuesto desde la app). Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.day_muscles'::regclass
      and contype = 'u'
      and conname = 'day_muscles_day_body_unique'
  ) then
    alter table public.day_muscles
      add constraint day_muscles_day_body_unique unique (day_of_week, body_part_id);
  end if;
end $$;

create table if not exists public.day_exercises (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  exercise_id bigint not null,
  position integer not null default 0,
  created_at text default (now()::text),
  constraint day_exercises_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint day_exercises_exercise_fk
    foreign key (exercise_id) references public.exercises_v2 (id) on delete cascade,
  constraint day_exercises_day_body_exercise_unique
    unique (day_of_week, body_part_id, exercise_id)
);

-- UNIQUE(day_of_week, body_part_id, exercise_id): evita duplicar el mismo
-- ejercicio dentro del mismo segmento diario. Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.day_exercises'::regclass
      and contype = 'u'
      and conname = 'day_exercises_day_body_exercise_unique'
  ) then
    alter table public.day_exercises
      add constraint day_exercises_day_body_exercise_unique
        unique (day_of_week, body_part_id, exercise_id);
  end if;
end $$;

-- ---------------- entrenamiento ----------------
create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  date text not null,
  completed integer not null default 0,
  created_at text default (now()::text),
  constraint workout_sessions_day_date_unique unique (day_of_week, date)
);

-- UNIQUE(day_of_week, date): una sola sesión por día (upsert idempotente).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.workout_sessions'::regclass
      and contype = 'u'
      and conname = 'workout_sessions_day_date_unique'
  ) then
    alter table public.workout_sessions
      add constraint workout_sessions_day_date_unique unique (day_of_week, date);
  end if;
end $$;

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  exercise_id bigint not null,
  set_number integer not null,
  weight_kg double precision,
  reps integer,
  set_type text default 'reps',
  time_seconds double precision,
  constraint workout_sets_session_fk
    foreign key (session_id) references public.workout_sessions (id) on delete cascade,
  constraint workout_sets_exercise_fk
    foreign key (exercise_id) references public.exercises_v2 (id) on delete cascade
);

-- ---------------- progreso y nutricion ----------------
create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  weight_kg double precision not null,
  notes text,
  created_at text default (now()::text)
);

create table if not exists public.nutrition_profile (
  user_id text primary key,
  daily_calories_goal integer not null,
  activity_level text not null,
  goal_type text not null,
  updated_at text,
  constraint nutrition_profile_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

create table if not exists public.daily_calories (
  id bigint generated by default as identity primary key,
  date text not null unique,
  calories_consumed double precision not null default 0,
  logged_at text default (now()::text)
);

-- UNIQUE(date): una sola fila de calorías por día (upsert idempotente).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.daily_calories'::regclass
      and contype = 'u'
      and conname = 'daily_calories_date_key'
  ) then
    alter table public.daily_calories
      add constraint daily_calories_date_key unique (date);
  end if;
end $$;

create table if not exists public.meal_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  meal_name text not null,
  calories double precision not null default 0,
  photo_uri text,
  created_at text default (now()::text)
);

create table if not exists public.weekly_meal_plan (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  date text,
  meal_type text not null,
  title text not null,
  description text,
  recipe text,
  ingredients_list text,
  servings_count integer not null default 1,
  expires_at text
);

-- ---------------- meta interna (por dispositivo) ----------------
create table if not exists public.app_meta (
  key text primary key,
  value text
);

-- ---------------- propietarios de filas (aislamiento multidispositivo) ----------------
-- Tabla auxiliar aditiva: registra a quÃ© usuario pertenece cada fila de las
-- tablas de usuario (workout_sessions, workout_sets, weight_logs, meal_logs, etc.)
-- para que el pull filtre exactamente lo que corresponde al usuario activo.
create table if not exists public.user_row_owners (
  table_name text not null,
  row_id bigint not null,
  user_id text not null,
  created_at text default (now()::text),
  primary key (table_name, row_id),
  constraint user_row_owners_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

-- 1. Crear tabla para el control de versiones de la app
create table if not exists public.app_versions (
  id bigint generated by default as identity primary key,
  is_active boolean default true,
  latest_version_code integer not null,
  latest_version_name text not null,
  download_url text not null,
  message text default 'Hay una nueva versión disponible de Anjuroela Fit. Por favor actualiza para continuar.',
  created_at text default (now()::text)
);

-- 2. Permisos para que la app lea la configuración anónimamente
grant select on table public.app_versions to anon;
alter table public.app_versions enable row level security;

drop policy if exists anon_select_app_versions on public.app_versions;
create policy anon_select_app_versions on public.app_versions 
  for select to anon using (true);

-- 3. Insertar el registro inicial de control (Versión 1)
-- Idempotente: no duplica registros si el script se vuelve a ejecutar.
insert into public.app_versions (is_active, latest_version_code, latest_version_name, download_url, message)
values (
  false, 
  1, 
  '1.0.0', 
  'https://drive.google.com/tu-enlace-de-drive', 
  '¡Nueva actualización disponible! Descárgala para disfrutar de los últimos cambios.'
)
on conflict (id) do nothing;

-- ============================================================
--  Accesos (anon) y Row Level Security
--  Permite lectura/escritura (incluido upsert) al rol 'anon'.
--  NOTA: en producciÃ³n se recomienda endurecer estas polÃ­ticas.
-- ============================================================
grant usage on schema public to anon;

grant all on table public.users to anon;
grant all on table public.user_profiles to anon;
grant all on table public.exercises to anon;
grant all on table public.body_parts to anon;
grant all on table public.exercises_v2 to anon;
grant all on table public.workouts to anon;
grant all on table public.workout_exercises to anon;
grant all on table public.meals to anon;
grant all on table public.meals_v2 to anon;
grant all on table public.progress to anon;
grant all on table public.weekly_schedule to anon;
grant all on table public.day_muscles to anon;
grant all on table public.day_exercises to anon;
grant all on table public.workout_sessions to anon;
grant all on table public.workout_sets to anon;
grant all on table public.weight_logs to anon;
grant all on table public.nutrition_profile to anon;
grant all on table public.daily_calories to anon;
grant all on table public.meal_logs to anon;
grant all on table public.weekly_meal_plan to anon;
grant all on table public.app_meta to anon;
grant all on table public.user_row_owners to anon;

grant usage, select on all sequences in schema public to anon;

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.body_parts enable row level security;
alter table public.exercises_v2 enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_exercises enable row level security;
alter table public.meals enable row level security;
alter table public.meals_v2 enable row level security;
alter table public.progress enable row level security;
alter table public.weekly_schedule enable row level security;
alter table public.day_muscles enable row level security;
alter table public.day_exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;
alter table public.weight_logs enable row level security;
alter table public.nutrition_profile enable row level security;
alter table public.daily_calories enable row level security;
alter table public.meal_logs enable row level security;
alter table public.weekly_meal_plan enable row level security;
alter table public.app_meta enable row level security;
alter table public.user_row_owners enable row level security;

-- Compatibilidad con instalaciones legacy donde 'user_id' aún era bigint
-- (FK del antiguo users(id)). Si alguna tabla con datos de usuario mantiene
-- la columna como bigint, se convierte a text y se re-direcciona su FK a
-- users(email) para que el upsert por correo y las políticas RLS funcionen.
-- Idempotente: sin columnas bigint remanentes no toca nada. Las filas
-- huérfanas (id numérico que ya no corresponde a ningún email) se descartan.
do $$
declare
  r record;
  con record;
begin
  for r in
    select t.table_name
    from information_schema.columns t
    where t.table_schema = 'public'
      and t.column_name = 'user_id'
      and t.data_type <> 'text'
  loop
    for con in
      select c.conname, tc.relname as table_name
      from pg_constraint c
      join pg_class tc on tc.oid = c.conrelid
      join pg_class rc on rc.oid = c.confrelid
      where c.contype = 'f'
        and tc.relname = r.table_name
        and rc.relname = 'users'
    loop
      execute 'alter table public.' || quote_ident(r.table_name)
        || ' drop constraint ' || quote_ident(con.conname);
    end loop;
    execute 'alter table public.' || quote_ident(r.table_name)
      || ' alter column user_id type text using user_id::text';
    execute 'delete from public.' || quote_ident(r.table_name)
      || ' where user_id::text not in (select email from public.users)';
    execute 'alter table public.' || quote_ident(r.table_name)
      || ' add constraint ' || quote_ident(r.table_name || '_user_fk')
      || ' foreign key (user_id) references public.users (email) on delete cascade';
  end loop;
end $$;

-- Identidad del usuario activo enviada por la app en la cabecera 'x-app-user'.
-- Las políticas RLS la usan para aislar los datos por usuario aunque la app
-- opere con la clave anónima (publishable). Devuelve '' (o null tras nullif)
-- cuando no hay sesión activa, negando el acceso a filas con propietario.
-- Patrón oficial de Supabase: current_setting('request.headers', true).
create or replace function public.app_user_email()
returns text
language sql
stable
as $$
  select nullif(current_setting('request.headers', true)::json ->> 'x-app-user', '')
$$;

-- Tablas de DATOS POR USUARIO (con columna propia en la misma fila): acceso
-- estrictamente limitado a la fila del usuario activo (email == cabecera).
drop policy if exists "anon_all_users" on public.users;
create policy anon_own_users on public.users
  for all to anon using (email::text = public.app_user_email())
  with check (email::text = public.app_user_email());
drop policy if exists "anon_all_user_profiles" on public.user_profiles;
create policy anon_own_user_profiles on public.user_profiles
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());
drop policy if exists "anon_all_nutrition_profile" on public.nutrition_profile;
create policy anon_own_nutrition_profile on public.nutrition_profile
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());
drop policy if exists "anon_all_meals_v2" on public.meals_v2;
create policy anon_own_meals_v2 on public.meals_v2
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());
drop policy if exists "anon_all_user_row_owners" on public.user_row_owners;
create policy anon_own_user_row_owners on public.user_row_owners
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());

-- Tablas con datos POR USUARIO pero SIN columna user_id: el dueño se conoce por
-- user_row_owners. SELECT/UPDATE/DELETE solo sobre filas propias (o todavía sin
-- dueño, p. ej. creadas localmente y aún no sincronizadas). El INSERT queda
-- abierto (el registro de propiedad ocurre tras el upsert en markOwnedRows).
drop policy if exists "anon_all_weekly_schedule" on public.weekly_schedule;
create policy anon_owned_weekly_schedule on public.weekly_schedule
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_schedule' and o.row_id = weekly_schedule.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_schedule' and o.row_id = weekly_schedule.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_day_muscles" on public.day_muscles;
create policy anon_owned_day_muscles on public.day_muscles
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_muscles' and o.row_id = day_muscles.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_muscles' and o.row_id = day_muscles.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_day_exercises" on public.day_exercises;
create policy anon_owned_day_exercises on public.day_exercises
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_exercises' and o.row_id = day_exercises.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_exercises' and o.row_id = day_exercises.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_workout_sessions" on public.workout_sessions;
create policy anon_owned_workout_sessions on public.workout_sessions
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sessions' and o.row_id = workout_sessions.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sessions' and o.row_id = workout_sessions.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_workout_sets" on public.workout_sets;
create policy anon_owned_workout_sets on public.workout_sets
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sets' and o.row_id = workout_sets.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sets' and o.row_id = workout_sets.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_weight_logs" on public.weight_logs;
create policy anon_owned_weight_logs on public.weight_logs
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weight_logs' and o.row_id = weight_logs.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weight_logs' and o.row_id = weight_logs.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_daily_calories" on public.daily_calories;
create policy anon_owned_daily_calories on public.daily_calories
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'daily_calories' and o.row_id = daily_calories.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'daily_calories' and o.row_id = daily_calories.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_meal_logs" on public.meal_logs;
create policy anon_owned_meal_logs on public.meal_logs
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'meal_logs' and o.row_id = meal_logs.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'meal_logs' and o.row_id = meal_logs.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_weekly_meal_plan" on public.weekly_meal_plan;
create policy anon_owned_weekly_meal_plan on public.weekly_meal_plan
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_meal_plan' and o.row_id = weekly_meal_plan.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_meal_plan' and o.row_id = weekly_meal_plan.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);

-- Tablas de CATÁLOGO global (ejercicios, partes del cuerpo) y tablas legacy
-- vacías que ya no se sincronizan (workouts, workout_exercises, exercises,
-- meals, progress) o de metadatos del dispositivo (app_meta): se mantienen
-- abiertas porque no contienen datos personales del usuario.
drop policy if exists "anon_all_exercises" on public.exercises;
create policy anon_all_exercises on public.exercises
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_body_parts" on public.body_parts;
create policy anon_all_body_parts on public.body_parts
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_exercises_v2" on public.exercises_v2;
create policy anon_all_exercises_v2 on public.exercises_v2
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_workouts" on public.workouts;
create policy anon_all_workouts on public.workouts
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_workout_exercises" on public.workout_exercises;
create policy anon_all_workout_exercises on public.workout_exercises
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_meals" on public.meals;
create policy anon_all_meals on public.meals
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_progress" on public.progress;
create policy anon_all_progress on public.progress
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_app_meta" on public.app_meta;
create policy anon_all_app_meta on public.app_meta
  for all to anon using (true) with check (true);
