-- ============================================================
--  Anjuroela Fit - Esquema para Supabase (replica 1:1 de SQLite)
--  Ejecutar completo en: Supabase Dashboard > SQL Editor.
--  Cada tabla local tiene su equivalente idÃ©ntico en nombre y columnas.
--  Mapeo de tipos: INTEGER -> integer, REAL -> double precision,
--  TEXT -> text, flags 0/1 -> integer (igual que en SQLite).
-- ============================================================

-- Este script es aditivo e idempotente: nunca elimina tablas ni registros
-- ACTIVOS. Una instalación que aún tenga users.id debe migrarse con una
-- migración versionada y respaldada; convertir su PK y sus FK automáticamente
-- requiere reconstruir tablas y no es seguro hacerlo al ejecutar el esquema base.

-- Única excepción a la regla aditiva: las tablas legacy que la app dejó de
-- usar (exercises, workouts, workout_exercises, meals, meals_v2 y progress)
-- se eliminan si aún existen en una instalación anterior. Están vacías tras la
-- limpieza de la app y no forman parte del esquema actual; el modelo activo usa
-- exercises_v2, meal_logs, weekly_meal_plan y el resto de tablas definidas aquí.
-- Idempotente: DROP TABLE IF EXISTS no estorba en instalaciones nuevas.
drop table if exists public.workout_exercises cascade;
drop table if exists public.workouts cascade;
drop table if exists public.exercises cascade;
drop table if exists public.meals cascade;
drop table if exists public.meals_v2 cascade;
drop table if exists public.progress cascade;

-- ---------------- usuarios ----------------
-- El EMAIL es la clave primaria (identidad unica de la cuenta, igual que en
-- SQLite local); el antiguo id identity queda fuera del modelo.
create table if not exists public.users (
  email text primary key,
  name text not null,
  password_hash text,
  auth_provider text default 'local',
  created_at text default (now()::text)
);

-- UNIQUE(email) (redundante con la PK) para compatibilidad con el upsert por
-- correo idempotente. Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.users'::regclass
      and contype = 'u'
      and conname = 'users_email_key'
  ) then
    alter table public.users
      add constraint users_email_key unique (email);
  end if;
end $$;

create table if not exists public.user_profiles (
  user_id text primary key,
  age integer,
  height double precision,
  current_weight double precision,
  target_weight double precision,
  goal_weeks integer,
  goal_date text,
  goal_status text default 'active',
  username text,
  gender text,
  created_at text default (now()::text),
  constraint user_profiles_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

-- UNIQUE(user_id): un solo perfil por usuario (necesario para el upsert
-- por user_id desde la app).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.user_profiles'::regclass
      and contype = 'u'
      and conname = 'user_profiles_user_id_key'
  ) then
    alter table public.user_profiles
      add constraint user_profiles_user_id_key unique (user_id);
  end if;
end $$;

-- Asegura que 'user_profiles' tenga TODAS las columnas del modelo actual en
-- instalaciones donde la tabla se creó con una versión anterior del script
-- (p. ej. sin 'age'): CREATE TABLE IF NOT EXISTS no añade columnas a una tabla
-- ya existente. Cada ADD COLUMN IF NOT EXISTS es idempotente y no borra datos.
do $$
begin
  alter table public.user_profiles add column if not exists age integer;
  alter table public.user_profiles add column if not exists height double precision;
  alter table public.user_profiles add column if not exists current_weight double precision;
  alter table public.user_profiles add column if not exists target_weight double precision;
  alter table public.user_profiles add column if not exists goal_weeks integer;
  alter table public.user_profiles add column if not exists goal_date text;
  alter table public.user_profiles add column if not exists goal_status text default 'active';
  alter table public.user_profiles add column if not exists username text;
  alter table public.user_profiles add column if not exists gender text;
  alter table public.user_profiles add column if not exists created_at text default (now()::text);
end $$;

-- ---------------- catalogo de ejercicios ----------------
create table if not exists public.body_parts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  is_active integer not null default 1,
  created_at text default (now()::text)
);

create table if not exists public.exercises_v2 (
  id bigint generated by default as identity primary key,
  name text not null,
  body_part_id bigint not null,
  description text,
  equipment text,
  mode text,
  is_active integer not null default 1,
  created_at text default (now()::text),
  constraint exercises_v2_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade
);

-- Soporte de circuitos por tiempo: tabla que describe un circuito (varios
-- ejercicios, trabajo/descanso y rondas) ligado a un día y a un músculo.
create table if not exists public.workout_circuits (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  name text not null,
  work_seconds real not null default 30,
  rest_seconds real not null default 60,
  rounds integer not null default 3,
  exercises_json text not null default '[]',
  created_at text default (now()::text),
  constraint workout_circuits_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint workout_circuits_day_part_uniq unique (day_of_week, body_part_id)
);

-- ---------------- planificacion semanal ----------------
create table if not exists public.weekly_schedule (
  id bigint generated by default as identity primary key,
  day_of_week text not null unique,
  body_part_id bigint,
  constraint weekly_schedule_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete set null
);

-- UNIQUE(day_of_week): un solo registro de plan por día de la semana
-- (upsert por conflicto en day_of_week desde la app). Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.weekly_schedule'::regclass
      and contype = 'u'
      and conname = 'weekly_schedule_day_of_week_key'
  ) then
    alter table public.weekly_schedule
      add constraint weekly_schedule_day_of_week_key unique (day_of_week);
  end if;
end $$;

create table if not exists public.day_muscles (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  position integer not null default 0,
  completed integer not null default 0,
  completed_date text,
  constraint day_muscles_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint day_muscles_day_body_unique unique (day_of_week, body_part_id)
);

-- UNIQUE(day_of_week, body_part_id): no asignar el mismo músculo dos veces el
-- mismo día (upsert por conflicto compuesto desde la app). Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.day_muscles'::regclass
      and contype = 'u'
      and conname = 'day_muscles_day_body_unique'
  ) then
    alter table public.day_muscles
      add constraint day_muscles_day_body_unique unique (day_of_week, body_part_id);
  end if;
end $$;

create table if not exists public.day_exercises (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  exercise_id bigint not null,
  position integer not null default 0,
  week_of text,
  created_at text default (now()::text),
  constraint day_exercises_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint day_exercises_exercise_fk
    foreign key (exercise_id) references public.exercises_v2 (id) on delete cascade,
  constraint day_exercises_day_body_exercise_unique
    unique (day_of_week, body_part_id, exercise_id)
);

-- UNIQUE(day_of_week, body_part_id, exercise_id): evita duplicar el mismo
-- ejercicio dentro del mismo segmento diario. Idempotente.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.day_exercises'::regclass
      and contype = 'u'
      and conname = 'day_exercises_day_body_exercise_unique'
  ) then
    alter table public.day_exercises
      add constraint day_exercises_day_body_exercise_unique
        unique (day_of_week, body_part_id, exercise_id);
  end if;
end $$;

-- week_of: etiqueta cada planificación con el LUNES de la semana en que se
-- eligió para aplicarle el RESET VISUAL POR DÍA (el día termina o cambia la
-- semana -> el plan se oculta sin borrarse de la BD; el historial y el
-- Progreso se conservan). ADD COLUMN IF NOT EXISTS: idempotente.
alter table public.day_exercises
  add column if not exists week_of text;

-- ---------------- entrenamiento ----------------
create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  date text not null,
  session_type text not null default 'routine',
  note text,
  completed integer not null default 0,
  calories_burned double precision not null default 0,
  created_at text default (now()::text),
  constraint workout_sessions_day_date_type_unique unique (day_of_week, date, session_type)
);

-- ADITIVO: sesiones ocasional ('session_type') y nota opcional. Deben añadirse
-- ANTES de crear la restricción UNIQUE compuesta que las referencia (las filas
-- de instalaciones anteriores quedan como 'routine', default, sin cambios).
alter table public.workout_sessions
  add column if not exists session_type text not null default 'routine';
alter table public.workout_sessions
  add column if not exists note text;

-- UNIQUE(day_of_week, date, session_type): una sesión de rutina + una ocasional
-- ('casual') pueden convivir el mismo día; el upsert por conflicto compuesto
-- desde la app es idempotente. Se reemplaza la antigua unicidad por día+date.
do $$
begin
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.workout_sessions'::regclass
      and contype = 'u'
      and conname = 'workout_sessions_day_date_unique'
  ) then
    alter table public.workout_sessions
      drop constraint workout_sessions_day_date_unique;
  end if;
end $$;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.workout_sessions'::regclass
      and contype = 'u'
      and conname = 'workout_sessions_day_date_type_unique'
  ) then
    alter table public.workout_sessions
      add constraint workout_sessions_day_date_type_unique
        unique (day_of_week, date, session_type);
  end if;
end $$;

-- ADD COLUMN IF NOT EXISTS: conserva sin cambios las sesiones de versiones
-- anteriores; las nuevas filas ya usan la columna de la definición completa.
alter table public.workout_sessions
  add column if not exists calories_burned double precision not null default 0;

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  exercise_id bigint not null,
  set_number integer not null,
  weight_kg double precision,
  reps integer,
  set_type text default 'reps',
  time_seconds double precision,
  constraint workout_sets_session_fk
    foreign key (session_id) references public.workout_sessions (id) on delete cascade,
  constraint workout_sets_exercise_fk
    foreign key (exercise_id) references public.exercises_v2 (id) on delete cascade
);

-- ---------------- progreso y nutricion ----------------
create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  weight_kg double precision not null,
  notes text,
  created_at text default (now()::text)
);

create table if not exists public.nutrition_profile (
  user_id text primary key,
  daily_calories_goal integer not null,
  activity_level text not null,
  goal_type text not null,
  updated_at text,
  constraint nutrition_profile_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

-- CREATE TABLE IF NOT EXISTS no completa tablas creadas por versiones
-- anteriores. Estas columnas las envía el formulario nutricional actual; se
-- agregan sin DEFAULT/NOT NULL para conservar sin cambios las filas legacy.
-- Las nuevas filas siguen usando las restricciones NOT NULL de la definición
-- completa cuando la tabla se crea desde cero.
alter table public.nutrition_profile
  add column if not exists daily_calories_goal integer;
alter table public.nutrition_profile
  add column if not exists goal_type text;

create table if not exists public.daily_calories (
  id bigint generated by default as identity primary key,
  date text not null unique,
  calories_consumed double precision not null default 0,
  logged_at text default (now()::text)
);

-- UNIQUE(date): una sola fila de calorías por día (upsert idempotente).
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.daily_calories'::regclass
      and contype = 'u'
      and conname = 'daily_calories_date_key'
  ) then
    alter table public.daily_calories
      add constraint daily_calories_date_key unique (date);
  end if;
end $$;

create table if not exists public.meal_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  meal_name text not null,
  calories double precision not null default 0,
  photo_uri text,
  created_at text default (now()::text)
);

create table if not exists public.weekly_meal_plan (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  date text,
  meal_type text not null,
  title text not null,
  description text,
  recipe text,
  ingredients_list text,
  servings_count integer not null default 1,
  expires_at text
);

-- ---------------- meta interna (por dispositivo) ----------------
create table if not exists public.app_meta (
  key text primary key,
  value text
);

-- ---------------- buffer de borrados pendientes (copia local) ----------------
-- Espejo del buffer local 'pending_deletions' de SQLite (cola de syncService
-- para propagar a la nube los borrados hechos sin conexión). NO se sincroniza
-- ni se restaura desde Supabase: en la nube solo existe como copia del esquema.
create table if not exists public.pending_deletions (
  id bigint generated by default as identity primary key,
  table_name text not null,
  row_id bigint,
  key_json text,
  user_id text not null,
  created_at text default (now()::text)
);

-- ---------------- propietarios de filas (aislamiento multidispositivo) ----------------
-- Tabla auxiliar aditiva: registra a quÃ© usuario pertenece cada fila de las
-- tablas de usuario (workout_sessions, workout_sets, weight_logs, meal_logs, etc.)
-- para que el pull filtre exactamente lo que corresponde al usuario activo.
create table if not exists public.user_row_owners (
  table_name text not null,
  row_id bigint not null,
  user_id text not null,
  created_at text default (now()::text),
  primary key (table_name, row_id),
  constraint user_row_owners_user_fk
    foreign key (user_id) references public.users (email) on delete cascade
);

-- 1. Crear tabla para el control de versiones de la app
create table if not exists public.app_versions (
  id bigint generated by default as identity primary key,
  is_active boolean default true,
  latest_version_code integer not null,
  latest_version_name text not null,
  download_url text not null,
  message text default 'Hay una nueva versión disponible de Anjuroela Fit. Por favor actualiza para continuar.',
  created_at text default (now()::text)
);

-- 2. Permisos para que la app lea la configuración anónimamente
grant select on table public.app_versions to anon;
alter table public.app_versions enable row level security;

drop policy if exists anon_select_app_versions on public.app_versions;
create policy anon_select_app_versions on public.app_versions 
  for select to anon using (true);

-- 3. Insertar el registro inicial de control (Versión 1)
-- Idempotente: no duplica registros si el script se vuelve a ejecutar.
insert into public.app_versions (is_active, latest_version_code, latest_version_name, download_url, message)
select
  false, 
  1, 
  '1.0.0', 
  'https://drive.google.com/tu-enlace-de-drive', 
  '¡Nueva actualización disponible! Descárgala para disfrutar de los últimos cambios.'
where not exists (
  select 1 from public.app_versions where latest_version_code = 1
);

-- ============================================================
--  Accesos (anon) y Row Level Security
--  Permite lectura/escritura (incluido upsert) al rol 'anon'.
--  NOTA: en producciÃ³n se recomienda endurecer estas polÃ­ticas.
-- ============================================================
grant usage on schema public to anon;

grant all on table public.users to anon;
grant all on table public.user_profiles to anon;
grant all on table public.body_parts to anon;
grant all on table public.exercises_v2 to anon;
grant all on table public.weekly_schedule to anon;
grant all on table public.day_muscles to anon;
grant all on table public.day_exercises to anon;
grant all on table public.workout_sessions to anon;
grant all on table public.workout_sets to anon;
grant all on table public.workout_circuits to anon;
grant all on table public.weight_logs to anon;
grant all on table public.nutrition_profile to anon;
grant all on table public.daily_calories to anon;
grant all on table public.meal_logs to anon;
grant all on table public.weekly_meal_plan to anon;
grant all on table public.app_meta to anon;
grant all on table public.pending_deletions to anon;
grant all on table public.user_row_owners to anon;

grant usage, select on all sequences in schema public to anon;

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.body_parts enable row level security;
alter table public.exercises_v2 enable row level security;
alter table public.weekly_schedule enable row level security;
alter table public.day_muscles enable row level security;
alter table public.day_exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;
alter table public.workout_circuits enable row level security;
alter table public.weight_logs enable row level security;
alter table public.nutrition_profile enable row level security;
alter table public.daily_calories enable row level security;
alter table public.meal_logs enable row level security;
alter table public.weekly_meal_plan enable row level security;
alter table public.app_meta enable row level security;
alter table public.user_row_owners enable row level security;
alter table public.pending_deletions enable row level security;

-- Las instalaciones legacy con user_id bigint requieren una migración
-- versionada que relacione explícitamente cada antiguo users.id con su email.
-- No se intenta convertir ni descartar filas aquí: transformar un número en
-- texto sin ese mapeo produciría referencias inválidas o pérdida de datos.

-- Identidad del usuario activo enviada por la app en la cabecera 'x-app-user'.
-- Las políticas RLS la usan para aislar los datos por usuario aunque la app
-- opere con la clave anónima (publishable). Devuelve '' (o null tras nullif)
-- cuando no hay sesión activa, negando el acceso a filas con propietario.
-- Patrón oficial de Supabase: current_setting('request.headers', true).
create or replace function public.app_user_email()
returns text
language sql
stable
as $$
  select nullif(current_setting('request.headers', true)::json ->> 'x-app-user', '')
$$;

-- Tablas de DATOS POR USUARIO (con columna propia en la misma fila): acceso
-- estrictamente limitado a la fila del usuario activo (email == cabecera).
-- Se eliminan todas las políticas legacy de user_profiles: algunas versiones
-- antiguas comparaban una columna id que ya no existe desde que email/user_id
-- es la identidad. Esto cambia políticas, nunca registros.
do $$
declare p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'user_profiles'
  loop
    execute format('drop policy if exists %I on public.user_profiles', p.policyname);
  end loop;
end $$;
drop policy if exists "anon_all_users" on public.users;
drop policy if exists "anon_own_users" on public.users;
create policy anon_own_users on public.users
  for all to anon using (email::text = public.app_user_email())
  with check (email::text = public.app_user_email());
create policy anon_own_user_profiles on public.user_profiles
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());
drop policy if exists "anon_all_nutrition_profile" on public.nutrition_profile;
drop policy if exists "anon_own_nutrition_profile" on public.nutrition_profile;
create policy anon_own_nutrition_profile on public.nutrition_profile
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());
drop policy if exists "anon_all_user_row_owners" on public.user_row_owners;
drop policy if exists "anon_own_user_row_owners" on public.user_row_owners;
create policy anon_own_user_row_owners on public.user_row_owners
  for all to anon using (user_id::text = public.app_user_email())
  with check (user_id::text = public.app_user_email());

-- Tablas con datos POR USUARIO pero SIN columna user_id: el dueño se conoce por
-- user_row_owners. SELECT/UPDATE/DELETE solo sobre filas propias (o todavía sin
-- dueño, p. ej. creadas localmente y aún no sincronizadas). El INSERT queda
-- abierto (el registro de propiedad ocurre tras el upsert en markOwnedRows).
drop policy if exists "anon_all_weekly_schedule" on public.weekly_schedule;
drop policy if exists "anon_owned_weekly_schedule" on public.weekly_schedule;
create policy anon_owned_weekly_schedule on public.weekly_schedule
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_schedule' and o.row_id = weekly_schedule.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_schedule' and o.row_id = weekly_schedule.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_day_muscles" on public.day_muscles;
drop policy if exists "anon_owned_day_muscles" on public.day_muscles;
create policy anon_owned_day_muscles on public.day_muscles
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_muscles' and o.row_id = day_muscles.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_muscles' and o.row_id = day_muscles.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_day_exercises" on public.day_exercises;
drop policy if exists "anon_owned_day_exercises" on public.day_exercises;
create policy anon_owned_day_exercises on public.day_exercises
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_exercises' and o.row_id = day_exercises.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'day_exercises' and o.row_id = day_exercises.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_workout_sessions" on public.workout_sessions;
drop policy if exists "anon_owned_workout_sessions" on public.workout_sessions;
create policy anon_owned_workout_sessions on public.workout_sessions
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sessions' and o.row_id = workout_sessions.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sessions' and o.row_id = workout_sessions.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_workout_sets" on public.workout_sets;
drop policy if exists "anon_owned_workout_sets" on public.workout_sets;
create policy anon_owned_workout_sets on public.workout_sets
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sets' and o.row_id = workout_sets.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_sets' and o.row_id = workout_sets.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_workout_circuits" on public.workout_circuits;
drop policy if exists "anon_owned_workout_circuits" on public.workout_circuits;
create policy anon_owned_workout_circuits on public.workout_circuits
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_circuits' and o.row_id = workout_circuits.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'workout_circuits' and o.row_id = workout_circuits.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_weight_logs" on public.weight_logs;
drop policy if exists "anon_owned_weight_logs" on public.weight_logs;
create policy anon_owned_weight_logs on public.weight_logs
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weight_logs' and o.row_id = weight_logs.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weight_logs' and o.row_id = weight_logs.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_daily_calories" on public.daily_calories;
drop policy if exists "anon_owned_daily_calories" on public.daily_calories;
create policy anon_owned_daily_calories on public.daily_calories
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'daily_calories' and o.row_id = daily_calories.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'daily_calories' and o.row_id = daily_calories.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_meal_logs" on public.meal_logs;
drop policy if exists "anon_owned_meal_logs" on public.meal_logs;
create policy anon_owned_meal_logs on public.meal_logs
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'meal_logs' and o.row_id = meal_logs.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'meal_logs' and o.row_id = meal_logs.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);
drop policy if exists "anon_all_weekly_meal_plan" on public.weekly_meal_plan;
drop policy if exists "anon_owned_weekly_meal_plan" on public.weekly_meal_plan;
create policy anon_owned_weekly_meal_plan on public.weekly_meal_plan
  for all to anon
  using (
    not exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_meal_plan' and o.row_id = weekly_meal_plan.id
    )
    or exists (
      select 1 from public.user_row_owners o
      where o.table_name = 'weekly_meal_plan' and o.row_id = weekly_meal_plan.id
        and o.user_id::text = public.app_user_email()
    )
  )
  with check (true);

-- Tablas de CATÁLOGO global (partes del cuerpo, ejercicios) y de metadatos del
-- dispositivo (app_meta): se mantienen abiertas porque no contienen datos
-- personales del usuario.
drop policy if exists "anon_all_body_parts" on public.body_parts;
create policy anon_all_body_parts on public.body_parts
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_exercises_v2" on public.exercises_v2;
create policy anon_all_exercises_v2 on public.exercises_v2
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_app_meta" on public.app_meta;
create policy anon_all_app_meta on public.app_meta
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_pending_deletions" on public.pending_deletions;
create policy anon_all_pending_deletions on public.pending_deletions
  for all to anon using (true) with check (true);

-- ============================================================
--  Borrado en cascada de la cuenta (datos del usuario)
--  Al eliminar una fila de `users` (desde el panel de Supabase o desde la
--  app), se borran también todas sus filas en las tablas de usuario que NO
--  tienen columna user_id y cuyo dueño se conoce solo por user_row_owners:
--  rutinas, sesiones, series, peso, comidas y plan semanal. Las tablas que ya
--  tienen FK a users (user_profiles, nutrition_profile, user_row_owners) se
--  limpian solas con ON DELETE CASCADE.
--  SECURITY DEFINER: el borrado se ejecuta como dueño de la función y no
--  depende de la cabecera x-app-user ni de RLS (funciona desde el panel).
--  Whitelist FIJA de tablas: nunca se usan table_name dinámicos de origen
--  externo, por lo que no hay riesgo de inyección/escalada pese al rol.
--  Idempotente: create or replace + drop trigger + create trigger permiten
--  re-ejecutar el script completo sin errores ni pérdida de datos.
-- ============================================================
create or replace function public.cascade_delete_user_data()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
begin
  foreach t in array array[
    'weekly_schedule','day_muscles','day_exercises','workout_sessions',
    'workout_sets','workout_circuits','weight_logs','meal_logs',
    'daily_calories','weekly_meal_plan'
  ]
  loop
    execute format(
      'delete from public.%I where id in
         (select row_id from public.user_row_owners
          where table_name = %L and user_id = %L)',
      t, t, old.email
    );
  end loop;
  return old;
end;
$$;

drop trigger if exists trg_users_cascade_delete on public.users;
create trigger trg_users_cascade_delete
  before delete on public.users
  for each row execute function public.cascade_delete_user_data();
