-- ============================================================
--  Anjuroela Fit - Esquema para Supabase (replica 1:1 de SQLite)
--  Ejecutar completo en: Supabase Dashboard > SQL Editor.
--  Cada tabla local tiene su equivalente idÃ©ntico en nombre y columnas.
--  Mapeo de tipos: INTEGER -> integer, REAL -> double precision,
--  TEXT -> text, flags 0/1 -> integer (igual que en SQLite).
-- ============================================================

-- ---------------- usuarios ----------------
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text,
  auth_provider text default 'local',
  google_id text,
  created_at text default (now()::text)
);

create table if not exists public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique,
  age integer,
  height double precision,
  current_weight double precision,
  target_weight double precision,
  goal_weeks integer,
  goal_date text,
  goal_status text default 'active',
  username text,
  created_at text default (now()::text),
  constraint user_profiles_user_fk
    foreign key (user_id) references public.users (id) on delete cascade
);

-- ---------------- catalogo de ejercicios ----------------
create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  name text not null,
  muscle_group text,
  description text,
  created_at text default (now()::text)
);

create table if not exists public.body_parts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  icon text,
  is_active integer not null default 1,
  created_at text default (now()::text)
);

create table if not exists public.exercises_v2 (
  id bigint generated by default as identity primary key,
  name text not null,
  body_part_id bigint not null,
  description text,
  equipment text,
  is_active integer not null default 1,
  created_at text default (now()::text),
  constraint exercises_v2_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade
);

-- ---------------- rutinas (legacy / solo copia) ----------------
create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  completed integer not null default 0,
  date text default (current_date::text),
  created_at text default (now()::text)
);

create table if not exists public.workout_exercises (
  id bigint generated by default as identity primary key,
  workout_id bigint not null,
  exercise_id bigint not null,
  sets integer not null default 3,
  reps integer not null default 10,
  weight double precision,
  constraint workout_exercises_workout_fk
    foreign key (workout_id) references public.workouts (id) on delete cascade,
  constraint workout_exercises_exercise_fk
    foreign key (exercise_id) references public.exercises (id) on delete cascade
);

-- ---------------- comidas (legacy / solo copia) ----------------
create table if not exists public.meals (
  id bigint generated by default as identity primary key,
  name text not null,
  calories integer,
  protein double precision,
  carbs double precision,
  fats double precision,
  date text default (current_date::text),
  created_at text default (now()::text)
);

create table if not exists public.meals_v2 (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  date text not null,
  meal_type text not null
    check (meal_type in ('desayuno', 'almuerzo', 'cena', 'snack')),
  image_uri text,
  description text,
  calories double precision default 0,
  protein_g double precision default 0,
  carbs_g double precision default 0,
  fat_g double precision default 0,
  notes text,
  created_at text default (now()::text),
  constraint meals_v2_user_fk
    foreign key (user_id) references public.users (id) on delete cascade
);

create table if not exists public.progress (
  id bigint generated by default as identity primary key,
  date text default (current_date::text),
  weight double precision,
  body_fat double precision,
  muscle_mass double precision,
  created_at text default (now()::text)
);

-- ---------------- planificacion semanal ----------------
create table if not exists public.weekly_schedule (
  id bigint generated by default as identity primary key,
  day_of_week text not null unique,
  body_part_id bigint,
  constraint weekly_schedule_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete set null
);

create table if not exists public.day_muscles (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  position integer not null default 0,
  completed integer not null default 0,
  completed_date text,
  constraint day_muscles_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint day_muscles_day_body_unique unique (day_of_week, body_part_id)
);

create table if not exists public.day_exercises (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  body_part_id bigint not null,
  exercise_id bigint not null,
  position integer not null default 0,
  created_at text default (now()::text),
  constraint day_exercises_body_part_fk
    foreign key (body_part_id) references public.body_parts (id) on delete cascade,
  constraint day_exercises_exercise_fk
    foreign key (exercise_id) references public.exercises_v2 (id) on delete cascade,
  constraint day_exercises_day_body_exercise_unique
    unique (day_of_week, body_part_id, exercise_id)
);

-- ---------------- entrenamiento ----------------
create table if not exists public.workout_sessions (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  date text not null,
  completed integer not null default 0,
  created_at text default (now()::text),
  constraint workout_sessions_day_date_unique unique (day_of_week, date)
);

create table if not exists public.workout_sets (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  exercise_id bigint not null,
  set_number integer not null,
  weight_kg double precision,
  reps integer,
  set_type text default 'reps',
  time_seconds double precision,
  constraint workout_sets_session_fk
    foreign key (session_id) references public.workout_sessions (id) on delete cascade,
  constraint workout_sets_exercise_fk
    foreign key (exercise_id) references public.exercises_v2 (id) on delete cascade
);

-- ---------------- progreso y nutricion ----------------
create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  weight_kg double precision not null,
  notes text,
  created_at text default (now()::text)
);

create table if not exists public.nutrition_profile (
  user_id bigint primary key,
  daily_calories_goal integer not null,
  activity_level text not null,
  goal_type text not null,
  updated_at text,
  constraint nutrition_profile_user_fk
    foreign key (user_id) references public.users (id) on delete cascade
);

create table if not exists public.daily_calories (
  id bigint generated by default as identity primary key,
  date text not null unique,
  calories_consumed double precision not null default 0,
  logged_at text default (now()::text)
);

create table if not exists public.meal_logs (
  id bigint generated by default as identity primary key,
  date text not null,
  meal_name text not null,
  calories double precision not null default 0,
  photo_uri text,
  created_at text default (now()::text)
);

create table if not exists public.weekly_meal_plan (
  id bigint generated by default as identity primary key,
  day_of_week text not null,
  date text,
  meal_type text not null,
  title text not null,
  description text,
  recipe text,
  ingredients_list text,
  servings_count integer not null default 1,
  expires_at text
);

-- ---------------- meta interna (por dispositivo) ----------------
create table if not exists public.app_meta (
  key text primary key,
  value text
);

-- ---------------- propietarios de filas (aislamiento multidispositivo) ----------------
-- Tabla auxiliar aditiva: registra a quÃ© usuario pertenece cada fila de las
-- tablas de usuario (workout_sessions, workout_sets, weight_logs, meal_logs, etc.)
-- para que el pull filtre exactamente lo que corresponde al usuario activo.
create table if not exists public.user_row_owners (
  table_name text not null,
  row_id bigint not null,
  user_id bigint not null,
  created_at text default (now()::text),
  primary key (table_name, row_id),
  constraint user_row_owners_user_fk
    foreign key (user_id) references public.users (id) on delete cascade
);

-- ============================================================
--  Accesos (anon) y Row Level Security
--  Permite lectura/escritura (incluido upsert) al rol 'anon'.
--  NOTA: en producciÃ³n se recomienda endurecer estas polÃ­ticas.
-- ============================================================
grant usage on schema public to anon;

grant all on table public.users to anon;
grant all on table public.user_profiles to anon;
grant all on table public.exercises to anon;
grant all on table public.body_parts to anon;
grant all on table public.exercises_v2 to anon;
grant all on table public.workouts to anon;
grant all on table public.workout_exercises to anon;
grant all on table public.meals to anon;
grant all on table public.meals_v2 to anon;
grant all on table public.progress to anon;
grant all on table public.weekly_schedule to anon;
grant all on table public.day_muscles to anon;
grant all on table public.day_exercises to anon;
grant all on table public.workout_sessions to anon;
grant all on table public.workout_sets to anon;
grant all on table public.weight_logs to anon;
grant all on table public.nutrition_profile to anon;
grant all on table public.daily_calories to anon;
grant all on table public.meal_logs to anon;
grant all on table public.weekly_meal_plan to anon;
grant all on table public.app_meta to anon;
grant all on table public.user_row_owners to anon;

grant usage, select on all sequences in schema public to anon;

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.exercises enable row level security;
alter table public.body_parts enable row level security;
alter table public.exercises_v2 enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_exercises enable row level security;
alter table public.meals enable row level security;
alter table public.meals_v2 enable row level security;
alter table public.progress enable row level security;
alter table public.weekly_schedule enable row level security;
alter table public.day_muscles enable row level security;
alter table public.day_exercises enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_sets enable row level security;
alter table public.weight_logs enable row level security;
alter table public.nutrition_profile enable row level security;
alter table public.daily_calories enable row level security;
alter table public.meal_logs enable row level security;
alter table public.weekly_meal_plan enable row level security;
alter table public.app_meta enable row level security;
alter table public.user_row_owners enable row level security;

drop policy if exists "anon_all_users" on public.users;
create policy anon_all_users on public.users
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_user_profiles" on public.user_profiles;
create policy anon_all_user_profiles on public.user_profiles
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_exercises" on public.exercises;
create policy anon_all_exercises on public.exercises
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_body_parts" on public.body_parts;
create policy anon_all_body_parts on public.body_parts
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_exercises_v2" on public.exercises_v2;
create policy anon_all_exercises_v2 on public.exercises_v2
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_workouts" on public.workouts;
create policy anon_all_workouts on public.workouts
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_workout_exercises" on public.workout_exercises;
create policy anon_all_workout_exercises on public.workout_exercises
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_meals" on public.meals;
create policy anon_all_meals on public.meals
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_meals_v2" on public.meals_v2;
create policy anon_all_meals_v2 on public.meals_v2
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_progress" on public.progress;
create policy anon_all_progress on public.progress
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_weekly_schedule" on public.weekly_schedule;
create policy anon_all_weekly_schedule on public.weekly_schedule
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_day_muscles" on public.day_muscles;
create policy anon_all_day_muscles on public.day_muscles
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_day_exercises" on public.day_exercises;
create policy anon_all_day_exercises on public.day_exercises
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_workout_sessions" on public.workout_sessions;
create policy anon_all_workout_sessions on public.workout_sessions
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_workout_sets" on public.workout_sets;
create policy anon_all_workout_sets on public.workout_sets
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_weight_logs" on public.weight_logs;
create policy anon_all_weight_logs on public.weight_logs
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_nutrition_profile" on public.nutrition_profile;
create policy anon_all_nutrition_profile on public.nutrition_profile
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_daily_calories" on public.daily_calories;
create policy anon_all_daily_calories on public.daily_calories
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_meal_logs" on public.meal_logs;
create policy anon_all_meal_logs on public.meal_logs
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_weekly_meal_plan" on public.weekly_meal_plan;
create policy anon_all_weekly_meal_plan on public.weekly_meal_plan
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_app_meta" on public.app_meta;
create policy anon_all_app_meta on public.app_meta
  for all to anon using (true) with check (true);
drop policy if exists "anon_all_user_row_owners" on public.user_row_owners;
create policy anon_all_user_row_owners on public.user_row_owners
  for all to anon using (true) with check (true);
